#
#     Highly configurable PaperDoll mod. Forked from Extra Player Renderer.
#     Copyright (C) 2024-2025  LucunJi(Original author), HappyRespawnanchor
#
#     This file is part of Ayame PaperDoll.
#
#     Ayame PaperDoll is free software: you can redistribute it and/or modify
#     it under the terms of the GNU Lesser General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     Ayame PaperDoll is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU Lesser General Public License for more details.
#
#     You should have received a copy of the GNU Lesser General Public License
#     along with Ayame PaperDoll.  If not, see <https://www.gnu.org/licenses/>.
#
# Gradle Settings
# Gradle JVM arguments
org.gradle.jvmargs=-Xmx2G
# Enable parallel build
org.gradle.parallel=true
# Mod Properties
# Mod license type
mod_license=LGPL-3.0-or-later
# Mod version
mod_version=4.4.4+26.2
# Mod name
mod_name=Ayame PaperDoll
# Mod ID
mod_id=ayame_paperdoll
# Archive name for the build output
mod_archives_name=ayame-paperdoll
# Mod description
mod_description=Highly configurable PaperDoll mod.\nForked from Extra Player Renderer.
# Maven group ID
mod_maven_group=org.ayamemc.ayamepaperdoll
# Mixin configuration file
mod_mixin_config=ayame-paperdoll.mixins.json
# Mod homepage URL
mod_homepage_url=https://modrinth.com/mod/ayame-paperdoll
# Mod source repository URL
mod_fabric_sources_url=https://github.com/AyameMC/Ayame-PaperDoll
# Mod issue tracker URL
mod_issues_url=https://github.com/AyameMC/Ayame-PaperDoll/issues
# Platform Settings
# Mod access widener path
mod_access_widener_name=ayame-paperdoll.accesswidener
# Supported platforms
enabled_platforms=fabric,neoforge
# Minecraft Properties
# Minecraft version
minecraft_version=26.2
# Dependencies Versions
# Fabric loader version
fabric_loader_version=0.19.3
# Fabric API version
fabric_api_version=0.152.1+26.2
# Fabric Minecraft version range
fabric_minecraft_version_range=>=26.2
# NeoForge version
neoforge_version=26.2.0.1-beta
# NeoForge Minecraft version range
neoforge_minecraft_version_range=[26.2,)
# Library Versions
# Fabric Mod Menu version
modmenu_version=20.0.0-alpha.1
